language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y build-essential freeglut3-dev libfreeimage-dev libgl1-mesa-dev libopenal-dev libpango1.0-dev libsdl-ttf2.0-dev libsndfile-dev libxinerama-dev
